# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"e\n\x04Note\x12\x16\n\tmember_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\n\n\x02to\x18\x04 \x03(\x05\x42\x0c\n\n_member_idB\x07\n\x05_name\"\x1e\n\nConnection\x12\x10\n\x08nickname\x18\x01 \x01(\t\"$\n\x0f\x43onnectionReply\x12\x11\n\tmember_id\x18\x01 \x01(\x05\x32\x8e\x01\n\nChatServer\x12\'\n\nChatStream\x12\x0b.grpc.Empty\x1a\n.grpc.Note0\x01\x12#\n\x08SendNote\x12\n.grpc.Note\x1a\x0b.grpc.Empty\x12\x32\n\x07\x43onnect\x12\x10.grpc.Connection\x1a\x15.grpc.ConnectionReplyb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_NOTE = DESCRIPTOR.message_types_by_name['Note']
_CONNECTION = DESCRIPTOR.message_types_by_name['Connection']
_CONNECTIONREPLY = DESCRIPTOR.message_types_by_name['ConnectionReply']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Note)
  })
_sym_db.RegisterMessage(Note)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTION,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Connection)
  })
_sym_db.RegisterMessage(Connection)

ConnectionReply = _reflection.GeneratedProtocolMessageType('ConnectionReply', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONREPLY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ConnectionReply)
  })
_sym_db.RegisterMessage(ConnectionReply)

_CHATSERVER = DESCRIPTOR.services_by_name['ChatServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _NOTE._serialized_start=29
  _NOTE._serialized_end=130
  _CONNECTION._serialized_start=132
  _CONNECTION._serialized_end=162
  _CONNECTIONREPLY._serialized_start=164
  _CONNECTIONREPLY._serialized_end=200
  _CHATSERVER._serialized_start=203
  _CHATSERVER._serialized_end=345
# @@protoc_insertion_point(module_scope)
